#**Iris-BPN-LearningFactors**

###**Created by Preksha Shah**

##**Introduction**
**Backpropagation Neural Network (BPN)** is a crucial algorithm in training artificial neural networks, especially for tasks requiring accurate predictions. It consists of two phases: forward propagation and backward propagation.

1. **Forward Propagation:** The input data is passed through the network layer by layer. Each neuron processes the input using weights and an activation function, producing an output. The final output is compared to the actual target value, and the error is calculated.

2. **Backward Propagation:** The error is propagated back through the network to update the weights. This involves calculating the gradient of the loss function with respect to each weight using the chain rule. The weights are then adjusted to minimize the error, guided by the learning rate and potentially enhanced by momentum.

The **learning factors** like learning rate and momentum play a significant role in how quickly and effectively the network learns. A well-tuned BPN adjusts these factors to optimize learning, resulting in faster convergence and better performance on tasks like classification or regression.

---

#**Q4: Create a program to implement learning factors in Back Propagation Neural Networks focusing on steps such as data handling, network architecture and implement learning factors for better learning. In the manual way done above.**

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler


In [ ]:
# Activation function (Sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
# Derivative of sigmoid (for backpropagation)
def sigmoid_derivative(x):
    return x * (1 - x)


In [ ]:
# Load Iris dataset
iris = load_iris()
X = iris.data  # Feature data
y = iris.target  # Target labels

In [ ]:
# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
# One Hot Encoding of the target variable
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y.reshape(-1, 1))


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
# Split dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
# Initialize network parameters
input_size = X_train.shape[1]  # Number of input features
hidden_size = 8                # Number of hidden neurons
output_size = y_train.shape[1] # Number of output neurons (classes)

In [ ]:
# Initialize weights and biases
np.random.seed(42)  # For reproducibility
weights_input_hidden = np.random.rand(input_size, hidden_size)
weights_hidden_output = np.random.rand(hidden_size, output_size)
bias_hidden = np.zeros((1, hidden_size))
bias_output = np.zeros((1, output_size))

In [ ]:
# Training parameters
epochs = 10000
learning_rate = 0.1

In [ ]:
# Training the network
for epoch in range(epochs):
    # Forward pass
    hidden_input = np.dot(X_train, weights_input_hidden) + bias_hidden
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_output) + bias_output
    final_output = sigmoid(final_input)

    # Compute loss (Mean Squared Error)
    loss = np.mean(np.square(y_train - final_output))

    # Backward pass
    output_error = y_train - final_output
    output_delta = output_error * sigmoid_derivative(final_output)

    hidden_error = np.dot(output_delta, weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_output)

    # Update weights and biases
    weights_hidden_output += np.dot(hidden_output.T, output_delta) * learning_rate
    bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
    weights_input_hidden += np.dot(X_train.T, hidden_delta) * learning_rate
    bias_hidden += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate

    # Print loss every 1000 epochs
    if epoch % 1000 == 0:
        print(f'Iris - Epoch {epoch}, Loss: {loss:.5f}')


Iris - Epoch 0, Loss: 0.51914
Iris - Epoch 1000, Loss: 0.01007
Iris - Epoch 2000, Loss: 0.00974
Iris - Epoch 3000, Loss: 0.00666
Iris - Epoch 4000, Loss: 0.00162
Iris - Epoch 5000, Loss: 0.00070
Iris - Epoch 6000, Loss: 0.00042
Iris - Epoch 7000, Loss: 0.00029
Iris - Epoch 8000, Loss: 0.00022
Iris - Epoch 9000, Loss: 0.00017


In [ ]:
# Test the network
hidden_input_test = np.dot(X_test, weights_input_hidden) + bias_hidden
hidden_output_test = sigmoid(hidden_input_test)

final_input_test = np.dot(hidden_output_test, weights_hidden_output) + bias_output
final_output_test = sigmoid(final_input_test)

In [ ]:
# Convert predictions to class labels
predictions = np.argmax(final_output_test, axis=1)
true_labels = np.argmax(y_test, axis=1)

In [ ]:
# Accuracy
accuracy = np.mean(predictions == true_labels)
print(f'\nIris - Test Accuracy: {accuracy:.2f}')


Iris - Test Accuracy: 1.00


In [ ]:
# Print final results
print("\nIris - Final weights and biases:")
print("Weights (Input to Hidden):")
print(weights_input_hidden)
print("Biases (Hidden Layer):")
print(bias_hidden)
print("Weights (Hidden to Output):")
print(weights_hidden_output)
print("Biases (Output Layer):")
print(bias_output)

print("\nIris - Predictions after training:")
print(predictions)


Iris - Final weights and biases:
Weights (Input to Hidden):
[[ 0.74406738  8.14909247  2.92758675 -1.18352539 -0.83794368 -0.29740104
   2.06879149 -4.69173863]
 [-1.820428    9.36901765 -0.36812533 -2.63542388 -0.69381085  1.67104589
  -1.28991436 -6.92123872]
 [ 2.75027356  3.24251504  1.71411134  0.11968824  4.42613326 -2.35605332
   8.74383425  6.66158811]
 [ 2.78620161  2.61291191 -0.10983211 10.32763658  1.20048966 -2.59881698
  -2.90342739  3.07353559]]
Biases (Hidden Layer):
[[ 3.03518785 -0.41913229  2.69027913 -8.98704902 -4.21893616 -1.96009524
  -8.18181835 -4.96011173]]
Weights (Hidden to Output):
[[-4.58042906  9.19036429 -2.77315068]
 [-0.22030248 -7.88945175  7.97939643]
 [-2.26754515  5.59466627 -4.59267649]
 [-0.24849726 -9.71413406  9.43806367]
 [-1.88258642 -3.72509206  4.35907928]
 [ 5.085044   -5.85695234 -3.81977557]
 [-0.62344708 -9.32625261  8.89423374]
 [-0.92539162 -6.61466755  6.73311657]]
Biases (Output Layer):
[[ 1.17949232  0.31221633 -7.97040594]]

Iris

### **Summary**
Weights and Biases: These matrices are crucial for the network's function. They are adjusted during training to minimize the prediction error.
Predictions: The output shows how well the network has learned to classify the test data based on the patterns it has learned from the training data.

---

##**Key Achievements**
1. **Backpropagation Neural Network Implementation:**Successfully built a BPN using NumPy, covering both forward and backward propagation steps.
Incorporated learning factors like the learning rate to improve training efficiency.
2. **Data Handling:** Utilized the Iris dataset, applying feature standardization and one-hot encoding to prepare data for the network.
3. **Network Architecture:** Designed a network with one hidden layer, initialized weights and biases, and set up the architecture for training.
4. **Training and Evaluation:** Trained the network over 10,000 epochs, reducing loss significantly and achieving high accuracy on test data.
Displayed key results, including final weights, biases, and predictions.

##**Conclusion**
The assignment effectively demonstrates the principles of Backpropagation Neural Networks (BPN), showcasing the implementation of forward and backward propagation, and the impact of learning factors. The successful training and evaluation on the Iris dataset confirm the network's ability to learn and make accurate predictions. The detailed results validate the network's performance and the effectiveness of the learning algorithm.

---
---